---
checks:
  method-complexity:
    config:
      threshold: 10
plugins:
  checkstyle:
    enabled: true
    config:
      file: "google_checks.xml"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      tests_patterns:
        - 'src/test/**'
        - 'src/integrationTest/**'
  pmd:
    enabled: true